-- MySQL Script generated by MySQL Workbench
-- Sun Nov 23 15:18:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quase_tudo_gostoso_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quase_tudo_gostoso_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quase_tudo_gostoso_java` DEFAULT CHARACTER SET utf8mb4 ;
USE `quase_tudo_gostoso_java` ;

-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`usuario` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `data_nascimento` DATE NULL,
  `cep` INT NULL,
  `genero` TINYINT NULL,
  `senha` VARCHAR(300) NOT NULL,
  `salt` VARCHAR(600) NOT NULL,
  `inscrito` DATETIME NOT NULL DEFAULT current_timestamp(),
  `uuid` VARCHAR(80) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`preparo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`preparo` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`preparo` (
  `idpreparo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modo_preparo` LONGTEXT NOT NULL,
  `urlvideo` VARCHAR(200) NULL,
  `tempopreparo` TIME NOT NULL,
  PRIMARY KEY (`idpreparo`),
  UNIQUE INDEX `idpreparo_UNIQUE` (`idpreparo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`dificuldade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`dificuldade` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`dificuldade` (
  `iddificuldade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dificuldade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddificuldade`),
  UNIQUE INDEX `iddificuldade_UNIQUE` (`iddificuldade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`custo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`custo` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`custo` (
  `idcusto` INT NOT NULL,
  `custo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcusto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`receita` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`receita` (
  `idreceita` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `imagem` LONGBLOB NULL,
  `cadastro_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idreceita`),
  UNIQUE INDEX `idreceita_UNIQUE` (`idreceita` ASC),
  INDEX `fk_receita_usuario1_idx` (`cadastro_idusuario` ASC),
  CONSTRAINT `fk_receita_usuario1`
    FOREIGN KEY (`cadastro_idusuario`)
    REFERENCES `quase_tudo_gostoso_java`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`categoria` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`categoria` (
  `idcategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(80) NOT NULL,
  `ativo` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC),
  UNIQUE INDEX `categoria_UNIQUE` (`categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`categoria_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`categoria_receita` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`categoria_receita` (
  `receita_idreceita` INT UNSIGNED NOT NULL,
  `categoria_idcategoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`receita_idreceita`, `categoria_idcategoria`),
  INDEX `fk_receita_has_categoria_categoria1_idx` (`categoria_idcategoria` ASC),
  INDEX `fk_receita_has_categoria_receita_idx` (`receita_idreceita` ASC),
  CONSTRAINT `fk_receita_has_categoria_receita`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `quase_tudo_gostoso_java`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_categoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `quase_tudo_gostoso_java`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`comentario` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`comentario` (
  `idcomentario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `receita_idreceita` INT UNSIGNED NOT NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  `comentario` LONGTEXT NULL,
  `nota` TINYINT NOT NULL,
  `datacomentario` DATETIME NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_receita_has_usuario_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_receita_has_usuario_receita1_idx` (`receita_idreceita` ASC),
  UNIQUE INDEX `idcomentario_UNIQUE` (`idcomentario` ASC),
  CONSTRAINT `fk_receita_has_usuario_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `quase_tudo_gostoso_java`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `quase_tudo_gostoso_java`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`ingrediente` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`ingrediente` (
  `idingrediente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ingrediente` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`idingrediente`),
  UNIQUE INDEX `idingrediente_UNIQUE` (`idingrediente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`dosagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`dosagem` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`dosagem` (
  `iddosagem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dosagem` VARCHAR(60) NOT NULL,
  `abreviacao` VARCHAR(45) NULL,
  PRIMARY KEY (`iddosagem`),
  UNIQUE INDEX `iddosagem_UNIQUE` (`iddosagem` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`ingrediente_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`ingrediente_receita` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`ingrediente_receita` (
  `ingrediente_idingrediente` INT UNSIGNED NOT NULL,
  `receita_idreceita` INT UNSIGNED NOT NULL,
  `quantidade` FLOAT NULL,
  `dosagem_iddosagem` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ingrediente_idingrediente`, `receita_idreceita`),
  INDEX `fk_ingrediente_has_receita_receita1_idx` (`receita_idreceita` ASC),
  INDEX `fk_ingrediente_has_receita_ingrediente1_idx` (`ingrediente_idingrediente` ASC),
  INDEX `fk_receita_ingrediente_dosagem1_idx` (`dosagem_iddosagem` ASC),
  CONSTRAINT `fk_ingrediente_has_receita_ingrediente1`
    FOREIGN KEY (`ingrediente_idingrediente`)
    REFERENCES `quase_tudo_gostoso_java`.`ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente_has_receita_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `quase_tudo_gostoso_java`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_ingrediente_dosagem1`
    FOREIGN KEY (`dosagem_iddosagem`)
    REFERENCES `quase_tudo_gostoso_java`.`dosagem` (`iddosagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`utensilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`utensilio` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`utensilio` (
  `idutensilio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `utensilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idutensilio`),
  UNIQUE INDEX `idutensilio_UNIQUE` (`idutensilio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`utensilio_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`utensilio_receita` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`utensilio_receita` (
  `receita_idreceita` INT UNSIGNED NOT NULL,
  `utensilio_idutensilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`receita_idreceita`, `utensilio_idutensilio`),
  INDEX `fk_receita_has_utensilio_utensilio1_idx` (`utensilio_idutensilio` ASC),
  INDEX `fk_receita_has_utensilio_receita1_idx` (`receita_idreceita` ASC),
  CONSTRAINT `fk_receita_has_utensilio_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `quase_tudo_gostoso_java`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_utensilio_utensilio1`
    FOREIGN KEY (`utensilio_idutensilio`)
    REFERENCES `quase_tudo_gostoso_java`.`utensilio` (`idutensilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`cozinha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`cozinha` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`cozinha` (
  `idcozinha` INT UNSIGNED NOT NULL,
  `cozinha` VARCHAR(85) NOT NULL,
  `ativo` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcozinha`),
  UNIQUE INDEX `idcozinha_UNIQUE` (`idcozinha` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`refeicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`refeicao` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`refeicao` (
  `idrefeicao` INT UNSIGNED NOT NULL,
  `refeicao` VARCHAR(65) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`idrefeicao`),
  UNIQUE INDEX `idrefeicao_UNIQUE` (`idrefeicao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`refeicao_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`refeicao_receita` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`refeicao_receita` (
  `receita_idreceita` INT UNSIGNED NOT NULL,
  `refeicao_idrefeicao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`receita_idreceita`, `refeicao_idrefeicao`),
  INDEX `fk_receita_has_refeicao_refeicao1_idx` (`refeicao_idrefeicao` ASC),
  INDEX `fk_receita_has_refeicao_receita1_idx` (`receita_idreceita` ASC),
  CONSTRAINT `fk_receita_has_refeicao_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `quase_tudo_gostoso_java`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_refeicao_refeicao1`
    FOREIGN KEY (`refeicao_idrefeicao`)
    REFERENCES `quase_tudo_gostoso_java`.`refeicao` (`idrefeicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quase_tudo_gostoso_java`.`cozinha_receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quase_tudo_gostoso_java`.`cozinha_receita` ;

CREATE TABLE IF NOT EXISTS `quase_tudo_gostoso_java`.`cozinha_receita` (
  `cozinha_idcozinha` INT UNSIGNED NOT NULL,
  `receita_idreceita` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cozinha_idcozinha`, `receita_idreceita`),
  INDEX `fk_cozinha_has_receita_receita1_idx` (`receita_idreceita` ASC),
  INDEX `fk_cozinha_has_receita_cozinha1_idx` (`cozinha_idcozinha` ASC),
  CONSTRAINT `fk_cozinha_has_receita_cozinha1`
    FOREIGN KEY (`cozinha_idcozinha`)
    REFERENCES `quase_tudo_gostoso_java`.`cozinha` (`idcozinha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cozinha_has_receita_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `quase_tudo_gostoso_java`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
